export interface V2DatabaseTableMeta {
  key: string
  mysqlTable: string
  name: string
  category: string
}

const toKey = (table: string) => table.replace(/_/g, '-')

const table = (mysqlTable: string, name: string, category: string): V2DatabaseTableMeta => ({
  key: toKey(mysqlTable),
  mysqlTable,
  name,
  category
})

export const V2_DATABASE_TABLES: V2DatabaseTableMeta[] = [
  table('animal', '牛只主档', 'v2 牛只与系谱'),
  table('animal_identifier', '牛只编号体系', 'v2 牛只与系谱'),
  table('animal_parentage', '系谱父母关系', 'v2 牛只与系谱'),
  table('stage_definition', '牛群阶段定义', 'v2 牛群圈舍'),
  table('herd_group', '牛群定义', 'v2 牛群圈舍'),
  table('farm_unit', '场区圈舍单元', 'v2 牛群圈舍'),
  table('animal_group_membership', '牛只入群历史', 'v2 牛群圈舍'),
  table('animal_pen_assignment', '牛只圈舍历史', 'v2 牛群圈舍'),
  table('group_pen_policy', '群舍匹配规则', 'v2 牛群圈舍'),
  table('group_transfer_request', '转群申请审批', 'v2 牛群圈舍'),
  table('unit_capacity_snapshot', '圈舍容量快照', 'v2 牛群圈舍'),
  table('business_calendar', '生产日历', 'v2 周期体系'),
  table('production_day_rule', '生产日规则', 'v2 周期体系'),
  table('production_shift', '生产班次', 'v2 周期体系'),
  table('time_day', '日维表', 'v2 周期体系'),
  table('time_month', '月维表', 'v2 周期体系'),
  table('time_year', '年维表', 'v2 周期体系'),
  table('time_period', '统一周期', 'v2 周期体系'),
  table('rolling_window_definition', '滚动窗口定义', 'v2 周期体系'),
  table('animal_time_index', '牛只周期索引', 'v2 周期体系'),
  table('trait_category', '性状分类', 'v2 表型泌乳'),
  table('trait_definition', '性状定义', 'v2 表型泌乳'),
  table('trait_method', '性状采集方法', 'v2 表型泌乳'),
  table('trait_observation_batch', '性状采集批次', 'v2 表型泌乳'),
  table('trait_observation', '性状观测明细', 'v2 表型泌乳'),
  table('trait_aggregation_rule', '性状聚合规则', 'v2 表型泌乳'),
  table('fact_cow_trait_day', '日性状事实', 'v2 表型泌乳'),
  table('fact_cow_trait_month', '月性状事实', 'v2 表型泌乳'),
  table('fact_cow_trait_year', '年性状事实', 'v2 表型泌乳'),
  table('fact_cow_trait_parity', '胎次性状事实', 'v2 表型泌乳'),
  table('fact_cow_trait_lactation', '泌乳期性状事实', 'v2 表型泌乳'),
  table('fact_lactation_305', '305 天泌乳事实', 'v2 表型泌乳'),
  table('animal_event', '统一事件明细', 'v2 事件繁殖'),
  table('event_reproduction_detail', '繁殖事件明细', 'v2 事件繁殖'),
  table('event_health_detail', '健康事件明细', 'v2 事件繁殖'),
  table('event_movement_detail', '转群事件明细', 'v2 事件繁殖'),
  table('event_production_detail', '生产事件明细', 'v2 事件繁殖'),
  table('event_medicine_detail', '用药事件明细', 'v2 事件繁殖'),
  table('parity_episode', '胎次周期', 'v2 事件繁殖'),
  table('reproduction_cycle', '繁殖周期', 'v2 事件繁殖'),
  table('lactation_episode', '泌乳期', 'v2 事件繁殖'),
  table('gestation_episode', '妊娠期', 'v2 事件繁殖'),
  table('dry_period_episode', '干奶期', 'v2 事件繁殖'),
  table('fact_event_count_day', '日事件次数', 'v2 事件繁殖'),
  table('fact_event_count_month', '月事件次数', 'v2 事件繁殖'),
  table('fact_event_count_year', '年事件次数', 'v2 事件繁殖'),
  table('fact_event_count_cycle', '繁殖周期事件次数', 'v2 事件繁殖'),
  table('fact_event_count_parity', '胎次事件次数', 'v2 事件繁殖'),
  table('fact_event_count_lactation', '泌乳期事件次数', 'v2 事件繁殖'),
  table('dictionary_category', '字典分类', 'v2 自定义体系'),
  table('dictionary_item', '字典项', 'v2 自定义体系'),
  table('custom_field_definition', '自定义字段定义', 'v2 自定义体系'),
  table('custom_field_value', '自定义字段值', 'v2 自定义体系'),
  table('field_promotion_request', '字段提升申请', 'v2 自定义体系'),
  table('duplicate_detection_rule', '导入去重规则', 'v2 自定义体系'),
  table('medicine', '药品定义', 'v2 药品库存'),
  table('medicine_batch', '药品批次', 'v2 药品库存'),
  table('medication_order', '用药医嘱', 'v2 药品库存'),
  table('medication_administration', '给药记录', 'v2 药品库存'),
  table('withdrawal_tracking', '休药期跟踪', 'v2 药品库存'),
  table('residue_test', '残留检测', 'v2 药品库存'),
  table('inventory_ledger', '库存流水', 'v2 药品库存'),
  table('device', '设备主档', 'v2 奶厅传感器'),
  table('device_channel', '设备通道', 'v2 奶厅传感器'),
  table('animal_device_assignment', '牛只设备绑定', 'v2 奶厅传感器'),
  table('milking_session', '挤奶场次', 'v2 奶厅传感器'),
  table('milking_visit', '单牛进厅记录', 'v2 奶厅传感器'),
  table('milk_measurement', '奶厅测量明细', 'v2 奶厅传感器'),
  table('sensor_reading', '传感器长表', 'v2 奶厅传感器'),
  table('data_quality_issue', '数据质量问题', 'v2 奶厅传感器'),
  table('research_project', '科研项目', 'v2 科研导出'),
  table('research_cohort_definition', '科研队列定义', 'v2 科研导出'),
  table('research_variable_set', '科研变量集', 'v2 科研导出'),
  table('research_extract_job', '科研抽取任务', 'v2 科研导出'),
  table('research_extract_filter', '科研抽取筛选', 'v2 科研导出'),
  table('research_extract_variable', '科研抽取变量', 'v2 科研导出'),
  table('research_dataset_snapshot', '科研数据快照', 'v2 科研导出'),
  table('research_dataset_artifact', '科研导出文件', 'v2 科研导出'),
  table('data_dictionary_snapshot', '数据字典快照', 'v2 科研导出'),
  table('omics_samples', '组学样本', 'v2 组学育种'),
  table('omics_datasets', '组学数据集', 'v2 组学育种'),
  table('omics_markers', '组学标记', 'v2 组学育种'),
  table('multi_omics_associations', '多组学关联', 'v2 组学育种'),
  table('breeding_analyses', '育种分析记录', 'v2 组学育种'),
  table('omics_dataset_sample', '组学数据集样本', 'v2 组学育种'),
  table('omics_feature', '组学特征', 'v2 组学育种'),
  table('omics_trait_link', '组学性状关联', 'v2 组学育种'),
  table('omics_artifact', '组学结果文件', 'v2 组学育种'),
  table('omics_module_runs', '组学模块运行', 'v2 组学育种'),
  table('omics_workflow_runs', '组学工作流运行', 'v2 组学育种'),
  table('omics_analysis_artifacts', '组学分析附件', 'v2 组学育种'),
  table('breeding_value_run', '育种值运行', 'v2 组学育种'),
  table('breeding_value', '育种值结果', 'v2 组学育种'),
  table('selection_index', '选择指数', 'v2 组学育种'),
  table('mating_recommendation', '选配推荐', 'v2 组学育种'),
  table('alert_rule', '预警规则', 'v2 预警工单'),
  table('alert_case', '预警事件', 'v2 预警工单'),
  table('work_order', '工单', 'v2 预警工单'),
  table('report_template', '报表模板', 'v2 报表审计'),
  table('report_metric_definition', '报表指标定义', 'v2 报表审计'),
  table('report_run', '报表运行', 'v2 报表审计'),
  table('report_run_item', '报表运行明细', 'v2 报表审计'),
  table('export_scope_definition', '导出范围定义', 'v2 报表审计'),
  table('report_period_filter', '报表周期筛选', 'v2 报表审计'),
  table('report_data_scope', '报表数据范围', 'v2 报表审计'),
  table('export_file', '导出文件', 'v2 报表审计'),
  table('permission_policy', '权限策略', 'v2 报表审计'),
  table('role_permission', '角色权限', 'v2 报表审计'),
  table('approval_workflow', '审批流程', 'v2 报表审计'),
  table('operation_audit_log', '操作审计', 'v2 报表审计'),
  table('correction_request', '数据修正申请', 'v2 报表审计'),
  table('derivation_recompute_job', '派生重算任务', 'v2 报表审计')
]

export const V2_DATABASE_STORE_SCHEMA =
  'id, animalId, animal_id, code, status, createdAt, created_at, updatedAt, updated_at'
